# Generated by Django 3.2 on 2022-05-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.posttype'),
        ),
    ]
